language: python
services:
  - docker
python:
  - "3.8.5"
install:
  - make deps
script:
  - make lint
  - make test_xunit
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: fathomless-reaches-93703
  api_key: ${HEROKU_API_KEY}
